### PR TITLE
Added different target_prop support in asapdiscovery-ml trainer.py

### PR DESCRIPTION
**Pull request by robby-wang**
## Description
Added different target_prop support in ml trainer.py. Very straightforward changes.

## Todos
- [x] Need code review

## Developers certificate of origin
- [x] I certify that this contribution is covered by the MIT license as defined in our [LICENSE](https://github.com/choderalab/asapdiscovery/blob/main/LICENSE) and adheres to the [**Developer Certificate of Origin**](https://developercertificate.org/).

### CODE REVIEW

**Comment by hmacdope** [comment]
@kaminow are you able to review here?

**Comment by kaminow** [comment]
yep sorry will do this afternoon

**Review by kaminow — APPROVED** [review]
looks good, thanks!

**Comment by robby-wang** [comment]
Merged to Main.

**Pull request merged**
