### PR TITLE
Coverage update 

### PR DESCRIPTION
**Pull request by jthorton**
## Description
Trying to update the coverage report to exclude the test files and lines which should be skipped like type checking lines.

## Todos
Notable points that this PR has either accomplished or will accomplish.
- [x] exclude test files
- [ ] exclude lines like type checking

## Questions
- [ ] Question 1 ..

## Status
- [ ] Ready to go

## Developers certificate of origin
- [ ] I certify that this contribution is covered by the MIT license as defined in our [LICENSE](https://github.com/choderalab/asapdiscovery/blob/main/LICENSE) and adheres to the [**Developer Certificate of Origin**](https://developercertificate.org/).

### CODE REVIEW

**Comment by hmacdope** [comment]
@jthorton would you mind if I merged here so I can get #832 in ASAP?

**Review by hmacdope — APPROVED** [review]

**Comment by jthorton** [comment]
@hmacdope did it actually work? I still see the test file coverage on this branch https://app.codecov.io/gh/choderalab/asapdiscovery/pull/871/tree/asapdiscovery-alchemy/asapdiscovery/alchemy/tests

**Comment by hmacdope** [comment]
no it did not by the looks of things.

**Comment by jthorton** [comment]
Note sure how to get this to work will close for now.

**Pull request closed without merging**
