### PR TITLE
[DNM] `asap-workflows` | add quickfix to cross_docking.py

### PR DESCRIPTION
**Pull request by apayne97**
## Description
A quickfix for #989 that gets around #997 

## Todos
Notable points that this PR has either accomplished or will accomplish.
- [x] add quickfix to cross-docking
- [ ] add quickfix to other workflows

## Status
- [x] Ready to go

## Developers certificate of origin
- [x] I certify that this contribution is covered by the MIT license as defined in our [LICENSE](https://github.com/choderalab/asapdiscovery/blob/main/LICENSE) and adheres to the [**Developer Certificate of Origin**](https://developercertificate.org/).

### CODE REVIEW

**Review by hmacdope — APPROVED** [review]
LGTM, merge when ready. If you can fix up the other ones that would be awesome, if not raise an issue.

**Comment by apayne97** [comment]
@hmacdope this didn't work, i got this error:
```
Traceback (most recent call last):
  File "/home/paynea/miniforge3/envs/asapdiscovery/bin/asap-docking", line 8, in <module>
    sys.exit(docking())
  File "/lila/home/paynea/miniforge3/envs/asapdiscovery/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/lila/home/paynea/miniforge3/envs/asapdiscovery/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/lila/home/paynea/miniforge3/envs/asapdiscovery/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/lila/home/paynea/miniforge3/envs/asapdiscovery/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/lila/home/paynea/miniforge3/envs/asapdiscovery/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/lila/data/chodera/paynea/asapdiscovery/asapdiscovery-workflows/asapdiscovery/workflows/docking_workflows/cli.py", line 269, in cross_docking
    cross_docking_workflow(inputs)
  File "/lila/data/chodera/paynea/asapdiscovery/asapdiscovery-workflows/asapdiscovery/workflows/docking_workflows/cross_docking.py", line 228, in cross_docking_workflow
    [r.posed_ligand for r in results if r is not None],
  File "/lila/data/chodera/paynea/asapdiscovery/asapdiscovery-workflows/asapdiscovery/workflows/docking_workflows/cross_docking.py", line 228, in <listcomp>
    [r.posed_ligand for r in results if r is not None],
AttributeError: 'list' object has no attribute 'posed_ligand'
```

**Comment by apayne97** [comment]
I just realized - I think this is only an issue if you're not using dask

**Comment by hmacdope** [comment]
Yeah this line removes 'None's` from the result list when using dask: `https://github.com/choderalab/asapdiscovery/blob/main/asapdiscovery-data/asapdiscovery/data/util/dask_utils.py#L193` We should homogenise the behaviour such that it also works without dask.

**Review by hmacdope — CHANGES_REQUESTED** [review]
Blocking here for DNM

**Comment by hmacdope** [comment]
#1018 should fix this for dask and non-dask runs.

**Comment by hmacdope** [comment]
Should no longer be necessary @apayne97. If you confirm we can close here. :)

**Comment by apayne97** [comment]
yep, #1018 did the trick!

**Pull request closed without merging**
