### PR TITLE
`data` Quality of Life improvements to split_fragment_screen.py

### PR DESCRIPTION
**Pull request by apayne97**
## Description
Provide a brief description of the PR's purpose here.

## Todos
- [x] make input and output directory not be the same place
- [x] overwrite output directory by default instead of failing if it exists

## Status
- [ ] Ready to go

## Developers certificate of origin
- [ ] I certify that this contribution is covered by the MIT license as defined in our [LICENSE](https://github.com/choderalab/asapdiscovery/blob/main/LICENSE) and adheres to the [**Developer Certificate of Origin**](https://developercertificate.org/).

### CODE REVIEW

**Review by hmacdope — APPROVED** [review]

**Comment by hmacdope** [comment]
@SiyangPeng would you be able to add your review here?

**Comment by SiyangPeng** [comment]
> @SiyangPeng would you be able to add your review here?

**Review by SiyangPeng — COMMENTED** [review]
Looks good to me.

**Comment by hmacdope** [comment]
@SiyangPeng the way to review is to click over on the `Files Changed` tab and then click `Review Changes` and leave a review that way. Closing the PR generally indicates it shouldn't be merged or worked on.  I get the confusion though with `closing` an issue, instead we want to `merge` this PR when everyone has reviewed.

**Review by SiyangPeng — APPROVED** [review]

**Comment by SiyangPeng** [comment]
> @SiyangPeng the way to review is to click over on the `Files Changed` tab and then click `Review Changes` and leave a review that way. Closing the PR generally indicates it shouldn't be merged or worked on. I get the confusion though with `closing` an issue, instead we want to `merge` this PR when everyone has reviewed.

Sorry about the confusion, I don't think I meant to close the PR, thank you for re-opening it.

**Comment by hmacdope** [comment]
> > @SiyangPeng the way to review is to click over on the `Files Changed` tab and then click `Review Changes` and leave a review that way. Closing the PR generally indicates it shouldn't be merged or worked on. I get the confusion though with `closing` an issue, instead we want to `merge` this PR when everyone has reviewed.
> 
> Sorry about the confusion, I don't think I meant to close the PR, thank you for re-opening it.

All good! Happens :)

**Pull request merged**
