### PR TITLE
Add protein prep for simulation

### PR DESCRIPTION
**Pull request by apayne97**
## Description
Extend on the previous work to make sure that the proteins we're prepping will do everything they need to do to work for simulating them.

## Todos
Notable points that this PR has either accomplished or will accomplish.
  - [ ] #139 
  - [ ] add separate protein prep code for prepping for simulation
  - [x] use tests from #129 for loading in models to see if the models work
  - [ ] add new protein prep code that will load a previously prepped `.oedu` and write out everything needed for docking / simulation (.sdf file, separate protein.pdb, .mol2 (?)) etc
  - [ ] add new protein prep code that will enumerate the protonation states

## Questions
- [ ] Question1

## Status
- [ ] Ready to go

### CODE REVIEW

**Comment by apayne97** [comment]
@JenkeScheen 
When I run this test case that should mimic this this error in `asap-datasets/prospective/2023/02_mers_retrospective_fep/02_fep`
```
ValueError: No template found for residue 8 (HIS).  The set of atoms matches HIP, but the bonds are different.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template
```
Instead, it doesn't have the same flaws as the pdb in `receptors/dimer/`. 
All the outputs look like this:
image

Where as the one you have in this directory looks like this:
image

**Comment by apayne97** [comment]
Based on your comment here https://github.com/choderalab/perses/pull/1145 I tried uncommenting this block but it didn't make a difference as to the appearance of the `H01` hydrogens.

https://github.com/choderalab/asapdiscovery/pull/142/commits/bc9c924e481871d8ec45e76e1d277b794256af59

**Comment by JenkeScheen** [comment]
it might be best not to pull from WIP folders such as `asap-datasets/prospective/2023/02_mers_retrospective_fep/02_fep` because those will involve manual tinkering with protonation states (likely the source of discrepancy here). Do you have a decent set of test PDBs to work with or would you like me to extract more? 

> Based on your comment here https://github.com/choderalab/perses/pull/1145 I tried uncommenting this block but it didn't make a difference as to the appearance of the H01 hydrogens

This ended up only working for me sporadically and I've since abandoned this approach. I observed the same thing, it usually doesn't make much of a difference.

**Comment by apayne97** [comment]
@JenkeScheen I would love to have a set of PDBs along with the pipeline you're using so that I can reproduce the error and hopefully fix it!

**Comment by apayne97** [comment]
Another question - how dependent is the rest of the pipeline on the `His41(0)-Cys145(0)-His163(0)` file-naming scheme? I kind of hate it but I don't have a better idea yet.

**Comment by JenkeScheen** [comment]
> Another question - how dependent is the rest of the pipeline on the His41(0)-Cys145(0)-His163(0) file-naming scheme? I kind of hate it but I don't have a better idea yet.

I'm not a big fan either (parentheses in file paths are a pain to work with), so any alternatives would be welcome. I do think it's valuable having the indication in the filename though. 

> @JenkeScheen I would love to have a set of PDBs along with the pipeline you're using so that I can reproduce the error and hopefully fix it!

Will get you some later today!

**Comment by JenkeScheen** [comment]
@apayne97 I was preparing some of this for you based on a system that gave me problems a few weeks ago:
`/lila/data/chodera/asap-datasets/prospective/for_ap/fraga_prepped_into_perses`

This particular perses run uses reference `P1835_0A` which has a 6 residue gap and protonation issues at his41 (for some reason openmm wants it protonated, not sure why). You'll find three folders:
- `default_pipeline` : standard procedure, i.e. pull protein from unprepped fragalysis folder. fails on his41 protonation, if fixed manually it will fail on the gap.
- `prepped_v3_into_pipeline_then_perses` : pulls your prepped (v3) fragalysis structure and preps it with the default pipeline. still fails on his41 (but not on the gap because it's been fixed by your prep), but runs fine when protonated manually
- `prepped_v3_straight_into_perses`: this completely ignores `00-prep-receptor.py` and makes perses pull the prepped (v3) protein directly. *This.. works?* Simulation seems to be running without issues. I recall trying doing this route during fall 2022 and then it didn't quite work (not if IIRC why).

I think that in order to get test cases for the work you're doing we need to:
1) get a whole collection of prepped fragalysis (v3 or whichever) *without* ligands
2) run every structure into perses and see if it passes correctly
3) collect all failed structures and compile them

I'll work on creating something like this today. Should I stick to v3?

This route would also be applicable to https://github.com/choderalab/asapdiscovery/issues/139. We should test the non-ligand prepped fragalysis set on both perses and vanilla MD (i.e. the pipeline for GIF generation) and see if there are differences (hopefully the failures match!)

**Comment by apayne97** [comment]
> I do think it's valuable having the indication in the filename though.
Agreed! Although I'm a little worried that this convention isn't very extensible if we end up wanting to specify like 10 protonation states. Maybe at that point we can save the different settings in a yaml file and just index the different combinations.

**Comment by apayne97** [comment]
> prepped_v3_straight_into_perses: this completely ignores 00-prep-receptor.py and makes perses pull the prepped (v3) protein directly. This.. works? Simulation seems to be running without issues. I recall trying doing this route during fall 2022 and then it didn't quite work (not if IIRC why).

This tracks with my investigation in the ASAP Notion page. Seems possible that the improvements to prepping have made the difference since Fall 2022 (including correctly fixing gaps)!

@JenkeScheen 
However this still has the problem of not specifying protonation states, which I can add next!
Were there any problems with input files when you tried the third approach? Should I update the protein prep script to generate apo protein pdbs and ligand sdfs?

**Comment by apayne97** [comment]
> @apayne97 I was preparing some of this for you based on a system that gave me problems a few weeks ago:
> /lila/data/chodera/asap-datasets/prospective/for_ap/fraga_prepped_into_perses

This is incredibly helpful, with README's and everything, thank you so much!

**Comment by JenkeScheen** [comment]
Alex, I'm running the complete fragalysis apo set through perses to see which fail, currently I'm about 200 structures in. It looks like ~99% are suitable for perses/OpenMM, so perhaps this might not be too much work after all. You can track the progress here: `/lila/data/chodera/asap-datasets/prospective/fragalysis_prepped_v3_noligs`

I'll do the same for MERS afterward. Hopefully we get a similar success rate.

> However this still has the problem of not specifying protonation states, which I can add next!

Yep, so it's starting to look like you'd only need to add this to *your* prepping script, then we can unify that prepping script to use it for all three methods (docking, vanillaMD and FE calcs).

> Were there any problems with input files when you tried the third approach? Should I update the protein prep script to generate apo protein pdbs and ligand sdfs?

Now that you mention it, there's something odd going on with `Mpro-P0394_0A_LON-WEI-9739a092-9`. I haven't had time to investigate but for some reason there is no source pdb (or it fails to copy.. I can chase this if it's not obvious when you check). Getting these apo structures is super easy, I just did something like:
```
with open(input_pdb, "r") as readfile, \
    open(output_pdb, "w") as writefile:

        reader = csv.reader(readfile)
        writer = csv.writer(writefile)
        for row in reader:
            if not "LIG" in row[0]:
                writer.writerow(row)
```

**Comment by apayne97** [comment]
```with open(input_pdb, "r") as readfile, 
    open(output_pdb, "w") as writefile:

        reader = csv.reader(readfile)
        writer = csv.writer(writefile)
        for row in reader:
            if not "LIG" in row[0]:
                writer.writerow(row)```

I'm surprised that bad things don't happen if there are remaining connect records between the LIG atoms when the LIG atoms no longer exist? But that's great!

**Comment by apayne97** [comment]
>Alex, I'm running the complete fragalysis apo set through perses to see which fail, currently I'm about 200 structures in. It looks like ~99% are suitable for perses/OpenMM, so perhaps this might not be too much work after all. You can track the progress here: /lila/data/chodera/asap-datasets/prospective/fragalysis_prepped_v3_noligs

This is great!

**Comment by apayne97** [comment]
@JenkeScheen 
> Now that you mention it, there's something odd going on with Mpro-P0394_0A_LON-WEI-9739a092-9. I haven't had time to investigate but for some reason there is no source pdb (or it fails to copy.. I can chase this if it's not obvious when you check).

For some reason this directory (and only this directory?) had a space at the end of the directory name. So if you tried to load in `Mpro-P0394_0A_LON-WEI-9739a092-9/*.pdb` it would fail. I moved it and recorded this in the README.

**Comment by JenkeScheen** [comment]
> I'm surprised that bad things don't happen if there are remaining connect records between the LIG atoms when the LIG atoms no longer exist? But that's great!

For once the PDB gods are merciful. (My guess is whatever parses the PDB ignores CONECTs where atoms are missing)

**Comment by JenkeScheen** [comment]
Okay, finished running the perses/OpenMM test on fragalysis/fauxalysis currently prepped structures. Fail/success is defined as whether the protein system passes and the simulation is started (after which it is killed); fail is when a residue throws a `ValueError` when OFF is applied (found by `grep "ValueError: No template found" */perses.out`). Results:

|            | Success (n) | Fail (n) | Fail (%) |
|------------|-------------|----------|----------|
| Fragalysis | 571         | 5        | 0.9      |
| Fauxalysis | 315         | 477      | 60.2     |

For `Fauxalysis` there is no difference in ratio between just comparing within chain A or B. 

I think that potentially it would make the most sense to start with the 5 failed `Fragalysis` structures, improve the prep script based on those? Then we can circle back and refactor the `Fauxalysis` generation script (do we want to? perhaps `Foldalysis` makes that work redundant?).

Meanwhile I'll run the whole of `Fragalysis` + `Fauxalysis` through the OpenMM vanilla MD pipeline because the PDB errors may well be different.

**Comment by apayne97** [comment]
> I think that potentially it would make the most sense to start with the 5 failed Fragalysis structures, improve the prep script based on those? 

Agreed! Looks like its just three kinds of errors:
```
Mpro-P0031_0A_BEN-DND-c852c98b-10/perses.out:ValueError: No template found for residue 2 (GLY).  The set of atoms matches GLY, but the bonds are different.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template
Mpro-P0057_0A_MAT-POS-6c284e65-1/perses.out:ValueError: No template found for residue 2 (GLY).  The set of atoms matches GLY, but the bonds are different.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template
Mpro-P1624_0A_EDJ-MED-1981ceba-2/perses.out:ValueError: No template found for residue 3 (GLY).  The set of atoms matches GLY, but the bonds are different.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template
Mpro-P1701_0A_MAT-POS-8695a11f-1/perses.out:ValueError: No template found for residue 3 (GLY).  The set of atoms matches GLY, but the bonds are different.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template
Mpro-P2402_0A_EDJ-MED-12c4873b-2/perses.out:ValueError: No template found for residue 459 (ASP).  The set of atoms matches CASP, but the bonds are different.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template
```

**Comment by apayne97** [comment]
I thought it might be because of the `ANISOU` lines remaining in the files, but it looks like some successes also have them so maybe not:
```
(base) paynea@lilac-ln02:/lila/data/chodera/asap-datasets/prospective/fragalysis_prepped_v3_noligs/prepped_without_ligs$ grep -l ANISOU */*/protein.pdb
fail/Mpro-P0031_0A_BEN-DND-c852c98b-10/protein.pdb
fail/Mpro-P0057_0A_MAT-POS-6c284e65-1/protein.pdb
fail/Mpro-P1624_0A_EDJ-MED-1981ceba-2/protein.pdb
fail/Mpro-P1701_0A_MAT-POS-8695a11f-1/protein.pdb
success/Mpro-P0772_0A_EDG-MED-ba1ac7b9-13/protein.pdb
success/Mpro-P0906_0A_JIN-POS-6dc588a4-6/protein.pdb
success/Mpro-P1015_0A_MAT-POS-4223bc15-2/protein.pdb
success/Mpro-x11541_0A_ALP-POS-6747fa38-1/protein.pd
```

**Comment by apayne97** [comment]
The first four failed files have a water in the file in the beginning of the file? not sure if this matters
```
/Users/alexpayne/lilac-mount-point/asap-datasets/prospective/fragalysis_prepped_v3_noligs/prepped_without_ligs/fail % grep -m 1 -B 1 HETATM */protein.pdb
Mpro-P0031_0A_BEN-DND-c852c98b-10/protein.pdb-ATOM     20  HA3 GLY A   2      -2.845   5.753 -12.432  1.00 20.00           H
Mpro-P0031_0A_BEN-DND-c852c98b-10/protein.pdb:HETATM 9367  O   HOH A   2      12.559  11.370  17.863  1.00 20.00           O
--
Mpro-P0057_0A_MAT-POS-6c284e65-1/protein.pdb-ATOM     20  HA3 GLY A   2      -3.028   5.481 -12.090  1.00 20.00           H
Mpro-P0057_0A_MAT-POS-6c284e65-1/protein.pdb:HETATM 9368  O   HOH A   2      12.567  11.287  17.872  1.00 20.00           O
--
Mpro-P1624_0A_EDJ-MED-1981ceba-2/protein.pdb-SEQRES  24 B  306  CYS SER GLY VAL THR PHE GLN
Mpro-P1624_0A_EDJ-MED-1981ceba-2/protein.pdb:HETATM 9364  O   HOH A   1      12.475  11.269  17.895  1.00 20.00           O
--
Mpro-P1701_0A_MAT-POS-8695a11f-1/protein.pdb-SEQRES  24 B  306  CYS SER GLY VAL THR PHE GLN
Mpro-P1701_0A_MAT-POS-8695a11f-1/protein.pdb:HETATM 9365  O   HOH A   1      12.540  11.352  17.941  1.00 20.00           O
--
Mpro-P2402_0A_EDJ-MED-12c4873b-2/protein.pdb-TER    9364      GLN B 306
Mpro-P2402_0A_EDJ-MED-12c4873b-2/protein.pdb:HETATM 9370  O   HOH W   1      12.462  11.332  17.962  1.00 35.90           O
```

**Comment by apayne97** [comment]
The issue with `Mpro-P2402_0A_EDJ-MED-12c4873b-2` is simpler, just a loop building failure around ASP153 (which is numbered 459 because its in chain B, 306+153 = 459)
image

**Comment by JenkeScheen** [comment]
okay, so running the prepped structures into *just* OpenMM to do vanillaMD results in the same ratios of success/fail, which makes sense:


Success (n) | Fail (n) | Fail (%)
-- | -- | --
Fragalysis | 571 | 5 | 0.9
Fauxalysis | 315 | 477 | 60.2

See `/lila/data/chodera/asap-datasets/prospective/openmm_to_gif_prepped` (here the ligand is not confidential)

**Comment by apayne97** [comment]
Here are the fauxalysis errors, for posterity:
```
$ grep ValueError: */*.out | grep -o rcsb.* | sort --unique

rcsb_4RSP_A/openmm.out:ValueError: No template found for residue 145 (CSO).  The set of atoms matches CCYS, but the bonds are different.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template
rcsb_4WMF_A/openmm.out:ValueError: No template found for residue 305 (MET).  The set of atoms is similar to NMET, but it is missing 1 hydrogen atoms.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template
rcsb_4WMF_B/openmm.out:ValueError: No template found for residue 305 (MET).  The set of atoms is similar to NMET, but it is missing 1 hydrogen atoms.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template
rcsb_4WMF_B/openmm.out:ValueError: No template found for residue 9 (PRO).  The set of atoms is similar to PRO, but it is missing 7 hydrogen atoms.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template
rcsb_4YLU_A/openmm.out:ValueError: No template found for residue 500 (VAL).  The set of atoms matches CVAL, but the bonds are different.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template
rcsb_4YLU_B/openmm.out:ValueError: No template found for residue 196 (VAL).  The set of atoms matches CVAL, but the bonds are different.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template
rcsb_4YLU_B/openmm.out:ValueError: No template found for residue 500 (VAL).  The set of atoms matches CVAL, but the bonds are different.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template
rcsb_5C3N_A/openmm.out:ValueError: No template found for residue 250 (SER).  The set of atoms is similar to SER, but it is missing 5 hydrogen atoms.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template
rcsb_5WKK_A/openmm.out:ValueError: No template found for residue 306 (VAL).  The set of atoms is similar to NVAL, but it is missing 1 hydrogen atoms.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template
rcsb_5WKM_A/openmm.out:ValueError: No template found for residue 194 (GLN).  The set of atoms matches GLY, but the bonds are different.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template
rcsb_5WKM_A/openmm.out:ValueError: No template found for residue 306 (VAL).  The set of atoms is similar to NVAL, but it is missing 1 hydrogen atoms.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template
rcsb_6VGZ_B/openmm.out:ValueError: No template found for residue 353 (LEU).  The set of atoms matches GLY, but the bonds are different.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template
rcsb_6VGZ_B/openmm.out:ValueError: No template found for residue 51 (LEU).  The set of atoms matches GLY, but the bonds are different.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template
rcsb_6VGZ_B/openmm.out:ValueError: No template found for residue 7 (LYS).  The set of atoms is similar to HID, but it is missing 8 atoms.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template
rcsb_6VH1_A/openmm.out:ValueError: No template found for residue 199 (GLN).  The set of atoms matches GLY, but the bonds are different.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template
rcsb_6VH1_B/openmm.out:ValueError: No template found for residue 199 (GLN).  The set of atoms matches GLY, but the bonds are different.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template
rcsb_6VH2_A/openmm.out:ValueError: No template found for residue 199 (GLN).  The set of atoms matches GLY, but the bonds are different.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template
rcsb_6VH2_A/openmm.out:ValueError: No template found for residue 72 (LYS).  The set of atoms matches GLY, but the bonds are different.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template
rcsb_6VH2_B/openmm.out:ValueError: No template found for residue 199 (GLN).  The set of atoms matches GLY, but the bonds are different.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template
rcsb_6VH3_A/openmm.out:ValueError: No template found for residue 79 (ASN).  The set of atoms is similar to NASN, but it is missing 1 hydrogen atoms.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template
rcsb_6VH3_A/openmm.out:ValueError: No template found for residue 7 (LYS).  The set of atoms matches GLY, but the bonds are different.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template
rcsb_7D3C_A/openmm.out:ValueError: No template found for residue 303 (VAL).  The set of atoms is similar to NVAL, but it is missing 1 hydrogen atoms.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template
rcsb_7D3C_B/openmm.out:ValueError: No template found for residue 303 (VAL).  The set of atoms is similar to NVAL, but it is missing 1 hydrogen atoms.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template
rcsb_7DR8_A/openmm.out:ValueError: No template found for residue 299 (ILE).  The set of atoms is similar to NILE, but it is missing 1 hydrogen atoms.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template
rcsb_7DR8_A/openmm.out:ValueError: No template found for residue 47 (GLN).  The set of atoms is similar to GLN, but it is missing 8 hydrogen atoms.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template
rcsb_7DR8_A/openmm.out:ValueError: No template found for residue 48 (LEU).  The set of atoms matches GLY, but the bonds are different.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template
rcsb_7DR8_B/openmm.out:ValueError: No template found for residue 48 (LEU).  The set of atoms matches GLY, but the bonds are different.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template
rcsb_7DR8_B/openmm.out:ValueError: No template found for residue 490 (GLN).  The set of atoms matches GLY, but the bonds are different.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template
rcsb_7DR9_A/openmm.out:ValueError: No template found for residue 23 (MET).  The set of atoms matches GLY, but the bonds are different.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template
rcsb_7DR9_A/openmm.out:ValueError: No template found for residue 46 (GLN).  The set of atoms is similar to NGLN, but it is missing 1 hydrogen atoms.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template
rcsb_7DR9_B/openmm.out:ValueError: No template found for residue 46 (GLN).  The set of atoms is similar to NGLN, but it is missing 1 hydrogen atoms.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template
rcsb_7DRA_A/openmm.out:ValueError: No template found for residue 456 (ASN).  The set of atoms matches GLY, but the bonds are different.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template
rcsb_7DRA_A/openmm.out:ValueError: No template found for residue 46 (GLN).  The set of atoms is similar to NGLN, but it is missing 1 hydrogen atoms.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template
rcsb_7DRA_B/openmm.out:ValueError: No template found for residue 158 (ASN).  The set of atoms matches GLY, but the bonds are different.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template
rcsb_7DRA_B/openmm.out:ValueError: No template found for residue 46 (GLN).  The set of atoms is similar to NGLN, but it is missing 1 hydrogen atoms.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template
rcsb_7T3Y_A/openmm.out:ValueError: No template found for residue 306 (HIS).  The set of atoms matches NGLY, but the bonds are different.  Perhaps the chain is missing a terminal group?  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template
rcsb_7T3Z_A/openmm.out:ValueError: No template found for residue 203 (LYS).  The set of atoms matches GLY, but the bonds are different.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template
rcsb_7T3Z_A/openmm.out:ValueError: No template found for residue 27 (MET).  The set of atoms is similar to MET, but it is missing 9 hydrogen atoms.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template
rcsb_7T40_A/openmm.out:ValueError: No template found for residue 49 (ASP).  The set of atoms is similar to ASP, but it is missing 4 hydrogen atoms.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template
rcsb_7T41_A/openmm.out:ValueError: No template found for residue 306 (VAL).  The set of atoms is similar to NVAL, but it is missing 1 hydrogen atoms.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template
rcsb_7TQ7_B/openmm.out:ValueError: No template found for residue 306 (VAL).  The set of atoms is similar to NVAL, but it is missing 1 hydrogen atoms.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template
rcsb_8CZV_B/openmm.out:ValueError: No template found for residue 226 (LYS).  The set of atoms matches GLY, but the bonds are different.  For more information, see https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#template
```

**Comment by JenkeScheen** [comment]
I've noticed that for cases where `The set of atoms matches [..], but the bonds are different`, often loading the receptor into PyMol, then writing out the PDB **with CONECT** gets rid of the issue. Perhaps for these cases it would simply be a matter of rewriting the CONECTs? Could OE be messing up the bonds?

**Comment by JenkeScheen** [comment]
For the `Fauxalysis` reference `PET-UNK-1901c25b-1_0A`, this is thrown:
```
ValueError: No template found for residue 500 (VAL).  The set of atoms matches CVAL, but the bonds are different.
```

Inspecting the residue in question:
image

Removing the OH2 resolves the issue and the protein works fine for simulation. Perhaps this is a clash with a water molecule and `spruce` (?) thinks the H2O is part of the backbone?

[just posting notes here as I go along]

**Comment by hmacdope** [comment]
Following discussion with @apayne97 we can close this as it has been probably superseeded by a number of PRs / issues eg #246 #276.

**Pull request closed without merging**
