### PR TITLE
Remove old docking scripts testing

### LINKED ISSUE #668: Docking CI needs to be cut down.
Currently it is taking over an hour, we need to remove some tests from docking CI so that it can run in a more reasonable timeframe. 

Once we start to cut on a 0.2.0 this will burden will be reduced.

### PR DESCRIPTION
**Pull request by hmacdope**
Fixes #668

Removes older docking CI.

## Developers certificate of origin
- [X] I certify that this contribution is covered by the MIT license as defined in our [LICENSE](https://github.com/choderalab/asapdiscovery/blob/main/LICENSE) and adheres to the [**Developer Certificate of Origin**](https://developercertificate.org/).

### CODE REVIEW

**Review by apayne97 — APPROVED** [review]
Yep, in light of #735 this makes perfect sense to me! @JenkeScheen are you still using `dock-small-scale-e2e` or can we get rid of that too?

**Comment by JenkeScheen** [comment]
I use what @hmacdope dictates me to use, so best to let him sign off on what can('t) be removed.

**Comment by hmacdope** [comment]
> Yep, in light of #735 this makes perfect sense to me! @JenkeScheen are you still using `dock-small-scale-e2e` or can we get rid of that too?

Lets leave that in as a backup just for now, we can fully remove once discussed (at in person week). I kind of want to cut a release that captures the side-by-side state before we remove everything. 

Side not @kaminow are you using `run-docking-oe` for the ML stuff? Just checking?

**Comment by hmacdope** [comment]
> > Yep, in light of #735 this makes perfect sense to me! @JenkeScheen are you still using `dock-small-scale-e2e` or can we get rid of that too?
> 
> Lets leave that in as a backup just for now, we can fully remove once discussed (at in person week). I kind of want to cut a release that captures the side-by-side state before we remove everything.
> 
> Side not @kaminow are you using `run-docking-oe` for the ML stuff? Just checking?

@kaminow bump on this query?

**Comment by kaminow** [comment]
that's what I have in the [example I put together](https://github.com/choderalab/asapdiscovery/blob/main/examples/ml_pipeline_v2.md), but I'm not particularly attached to it if it's being deprecated. will just need to update the example with the new command

**Comment by hmacdope** [comment]
> that's what I have in the [example I put together](https://github.com/choderalab/asapdiscovery/blob/main/examples/ml_pipeline_v2.md), but I'm not particularly attached to it if it's being deprecated. will just need to update the example with the new command

Ok so good to merge here.

**Pull request merged**
