### PR TITLE
`ASAP-Simulate`: update small molecule FF in `VanillaMDSimulator`

### PR DESCRIPTION
**Pull request by jthorton**
## Description
Provide a brief description of the PR's purpose here.

This PR exposed the small molecule OpenFF force field used in the `VanillaMDSimulator` as an option and updates the default to `openff-2.2.0.offxml` to take advantage of the improved sulfamide modelled geometries! 

## Todos
Notable points that this PR has either accomplished or will accomplish.
- [x] update the default small molecule force field
- [x] expose setting the force field as an option in the schema

## Questions
- [ ] Should we also expose the protein force field? 

## Status
- [x] Ready to go

## Developers certificate of origin
- [x] I certify that this contribution is covered by the MIT license as defined in our [LICENSE](https://github.com/choderalab/asapdiscovery/blob/main/LICENSE) and adheres to the [**Developer Certificate of Origin**](https://developercertificate.org/).

### CODE REVIEW

**Comment by JenkeScheen** [comment]
should the new version of openff be pinned in the env yamls?

**Comment by jthorton** [comment]
@JenkeScheen we don't have any pins around the openff-toolkit so it should always install the newest version but we could pin it just to ensure the default always works!

**Review by JenkeScheen — APPROVED** [review]
yep go ahead and pin a minimal version and then merge!

**Comment by JenkeScheen** [comment]
no need to expose yet imo

**Comment by hmacdope** [comment]
Thanks for doing this!

**Comment by hmacdope** [comment]
> @JenkeScheen we don't have any pins around the openff-toolkit so it should always install the newest version but we could pin it just to ensure the default always works!

We should pin just to be clear.

**Pull request merged**
