### PR TITLE
Fix code coverage

### PR DESCRIPTION
**Pull request by mikemhenry**
## Description
Provide a brief description of the PR's purpose here.

## Todos
Notable points that this PR has either accomplished or will accomplish.
  - [ ] TODO 1

## Questions
- [ ] Question1

## Status
- [ ] Ready to go

### CODE REVIEW

**Comment by mikemhenry** [comment]
Locally, the coverage report looks correct, so I am not sure why on GHA it only shows test coverage and not package coverage

**Comment by mikemhenry** [comment]
Sweet, making the installation editable `-e` fixed it! 
Now to make `-n auto` work for everything

**Comment by mikemhenry** [comment]
This is looking great! Can you add  --durations=10 

To the pytest call? That will print the slowest 10 tests which can work on making faster in a future PR

**Comment by hmacdope** [comment]
> This is looking great! Can you add --durations=10
> 
> To the pytest call? That will print the slowest 10 tests which can work on making faster in a future PR

Doneskies.

**Review by hmacdope — APPROVED** [review]
@mikemhenry I am going to approve here, feel free to merge when CI green / you are happy. :)

**Comment by hmacdope** [comment]
@mikemhenry the macos tests seems to be hanging? Not sure why exactly.

**Comment by apayne97** [comment]
> @mikemhenry the macos tests seems to be hanging? Not sure why exactly.
I tried re-running the tests and it looks like its happening here:

```
asapdiscovery-docking/asapdiscovery/docking/tests/test_docking.py::test_docking_kwargs[subprocess-ml1-False-False---omega] 
```
so running run-docking-oe with these args is stalling:
--gat
--omega

**Comment by mikemhenry** [comment]
We only have 5 OSX runners org wide so I am working on reducing the amount of OSX testing we do, but I am not sure why it seems to fail. I will try and re-run it

**Comment by apayne97** [comment]
```
Traceback (most recent call last):
  File "/Users/alexpayne/opt/anaconda3/envs/ad-3.9/bin/run-docking-oe", line 8, in <module>
    sys.exit(main())
  File "/Users/alexpayne/Scientific_Projects/covid-moonshot-ml/asapdiscovery-docking/asapdiscovery/docking/scripts/run_docking_oe.py", line 560, in main
    GAT_model = GATInference(gat_model_string)
  File "/Users/alexpayne/Scientific_Projects/covid-moonshot-ml/asapdiscovery-ml/asapdiscovery/ml/inference/inference.py", line 171, in __init__
    super().__init__(
  File "/Users/alexpayne/Scientific_Projects/covid-moonshot-ml/asapdiscovery-ml/asapdiscovery/ml/inference/inference.py", line 99, in __init__
    self.model = self.build_model(self.model_components.type, **build_model_kwargs)
  File "/Users/alexpayne/Scientific_Projects/covid-moonshot-ml/asapdiscovery-ml/asapdiscovery/ml/inference/inference.py", line 128, in build_model
    model = build_model(model_type, **kwargs)
  File "/Users/alexpayne/Scientific_Projects/covid-moonshot-ml/asapdiscovery-ml/asapdiscovery/ml/utils.py", line 235, in build_model
    import mtenn.conversion_utils
  File "/Users/alexpayne/opt/anaconda3/envs/ad-3.9/lib/python3.9/site-packages/mtenn/__init__.py", line 5, in <module>
    from . import conversion_utils
  File "/Users/alexpayne/opt/anaconda3/envs/ad-3.9/lib/python3.9/site-packages/mtenn/conversion_utils/__init__.py", line 1, in <module>
    from .e3nn import E3NN
  File "/Users/alexpayne/opt/anaconda3/envs/ad-3.9/lib/python3.9/site-packages/mtenn/conversion_utils/e3nn.py", line 7, in <module>
    from e3nn.nn.models.gate_points_2101 import Network
  File "/Users/alexpayne/opt/anaconda3/envs/ad-3.9/lib/python3.9/site-packages/e3nn/nn/models/gate_points_2101.py", line 11, in <module>
    from torch_geometric.data import Data
  File "/Users/alexpayne/opt/anaconda3/envs/ad-3.9/lib/python3.9/site-packages/torch_geometric/__init__.py", line 4, in <module>
    import torch_geometric.data
  File "/Users/alexpayne/opt/anaconda3/envs/ad-3.9/lib/python3.9/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/Users/alexpayne/opt/anaconda3/envs/ad-3.9/lib/python3.9/site-packages/torch_geometric/data/data.py", line 20, in <module>
    from torch_sparse import SparseTensor
  File "/Users/alexpayne/opt/anaconda3/envs/ad-3.9/lib/python3.9/site-packages/torch_sparse/__init__.py", line 39, in <module>
    from .storage import SparseStorage  # noqa
  File "/Users/alexpayne/opt/anaconda3/envs/ad-3.9/lib/python3.9/site-packages/torch_sparse/storage.py", line 7, in <module>
    from torch_sparse.utils import Final, index_sort
  File "/Users/alexpayne/opt/anaconda3/envs/ad-3.9/lib/python3.9/site-packages/torch_sparse/utils.py", line 5, in <module>
    import torch_sparse.typing
  File "/Users/alexpayne/opt/anaconda3/envs/ad-3.9/lib/python3.9/site-packages/torch_sparse/typing.py", line 2, in <module>
    import pyg_lib  # noqa
  File "/Users/alexpayne/opt/anaconda3/envs/ad-3.9/lib/python3.9/site-packages/pyg_lib/__init__.py", line 38, in <module>
    load_library('libpyg')
  File "/Users/alexpayne/opt/anaconda3/envs/ad-3.9/lib/python3.9/site-packages/pyg_lib/__init__.py", line 35, in load_library
    torch.ops.load_library(spec.origin)
  File "/Users/alexpayne/opt/anaconda3/envs/ad-3.9/lib/python3.9/site-packages/torch/_ops.py", line 643, in load_library
    ctypes.CDLL(path)
  File "/Users/alexpayne/opt/anaconda3/envs/ad-3.9/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/alexpayne/opt/anaconda3/envs/ad-3.9/lib/python3.9/site-packages/libpyg.so, 0x0006): Symbol not found: __ZN2at4_ops11randint_low4callExxN3c108ArrayRefIxEENS2_8optionalINS2_10ScalarTypeEEENS5_INS2_6LayoutEEENS5_INS2_6DeviceEEENS5_IbEE
  Referenced from: <1C537960-90F1-3DD9-82AC-5D9140745C11> /Users/alexpayne/opt/anaconda3/envs/ad-3.9/lib/python3.9/site-packages/libpyg.so
  Expected in:     <5B2236FC-D3DD-34B7-AD69-9723550D975A> /Users/alexpayne/opt/anaconda3/envs/ad-3.9/lib/python3.9/site-packages/torch/lib/libtorch_cpu.dylib
```

**Comment by mikemhenry** [comment]
@apayne97 that kind of error is an ABI issue, `libtorch_cpu.dylib` is trying to call `__ZN2at4_ops11randint_low4callExxN3c108ArrayRefIxEENS2_8optionalINS2_10ScalarTypeEEENS5_INS2_6LayoutEEENS5_INS2_6DeviceEEENS5_IbEE` from `libpyg.so` but can't find it

When I re-ran the test on macOS, it passed, I will cancel the one that is running now and restart it since it has been running for 50min, so somewhere we have a test that can either go in an inf loop, or needs a timeout

**Comment by mikemhenry** [comment]
Now only getting that frag error

**Comment by mikemhenry** [comment]
Not sure why that test keeps hanging but I am going to merge this in

**Pull request merged**
