### PR TITLE
Add new models trained with better learning rate

### PR DESCRIPTION
**Pull request by kaminow**
Add new SchNet model trained with a lower learning rate to avoid the weights collapsing. These models were trained using `mtenn v0.4.0`, so probably shouldn't be used with previous versions. This is the version that's pinned in the `asapdiscovery` conda env files, so it shouldn't cause any issues.

### CODE REVIEW

**Review by hmacdope — APPROVED** [review]
LGTM!

**Comment by hmacdope** [comment]
@kaminow need to fix for CI, seems like we were checking that the pIC50 > 0 but is ~ -2000, for our test case. Is this expected?

**Comment by kaminow** [comment]
no it absolutely is not lol, I'm looking into it

**Comment by kaminow** [comment]
this should work now. it turns out there was a config option that wasn't getting passed around the way I thought it was, so I've included it explicitly now in the model `config.json` file. as a side note, this is something that won't be an issue once #601 is finished, since it was just a matter of me being dumb and not properly keeping track of all the model config options

**Comment by kaminow** [comment]
@hmacdope looks like everything is green now! I'll leave the merging up to you in case you want to take one last look

**Comment by hmacdope** [comment]
> @hmacdope looks like everything is green now! I'll leave the merging up to you in case you want to take one last look

I am just going to fix that test that you had to change so we dont have to re-fix it all the time but other than that thanks so much for this, looks great.

**Review by hmacdope — APPROVED** [review]

**Pull request merged**
