### PR TITLE
Add new targets

### PR DESCRIPTION
**Pull request by JenkeScheen**
resolves https://github.com/choderalab/asapdiscovery/issues/563

Adding these bad boys throughout:
- `DENV-NS2B-NS3`
  - [x] Update manifold_data_tags.yaml
  - [x] Put in a SEQRES as a yaml
  - [x] Put in a master structure to align to.
  - [x] Define subpockets and colors
- `ZIKV-NS2B-NS3`
  - [x] Update manifold_data_tags.yaml
  - [x] Put in a SEQRES as a yaml
  - [x] Put in a master structure to align to.
  - [x] Define subpockets and colors
    - -> may need to also take care of allosteric site 
- `EV-D68-3C`
  - [x] Update manifold_data_tags.yaml
  - [x] Put in a SEQRES as a yaml
  - [x] Put in a master structure to align to.
  - [x] Define subpockets and colors
- `EV-A71-3C`
  - [x] Update manifold_data_tags.yaml
  - [x] Put in a SEQRES as a yaml
  - [x] Put in a master structure to align to.
  - [x] Define subpockets and colors

### CODE REVIEW

**Comment by JenkeScheen** [comment]
these target names are making my head spin - we should get someone from structural biology/ datacore to review what we've implemented here, once ready for review.

**Comment by JenkeScheen** [comment]
I'm adding preliminary literature structures as master references for:

- A71: PDB 7L8H
- NS2B-NS3: PDB 5H4I

**Comment by JenkeScheen** [comment]
I created a doc that outlines the steps required for adding new targets in the future: https://www.notion.so/asapdiscovery/HOWTO-Adding-new-target-specifications-to-codebase-e701d1ed16424a838fd97a1b0a7add12?pvs=4. This contains an overview of the steps and recommendations on how to do it in the least painful way.

**Comment by JenkeScheen** [comment]
in a future PR, we can try to pull data from asapdiscovery.org.

**Review by hmacdope — APPROVED** [review]
LGTM! thanks for doing this.

**Pull request merged**
