### PR TITLE
`ASAP-Alchemy`: Prediction no overlapping experimental data

### PR DESCRIPTION
**Pull request by jthorton**
## Description
This PR fixes a bug where absolute predictions become `nan` when experimental data is provided but does not overlap with the ligands in the network. We now only shift the data if at least one ligand in the network has an experimental data point this also means interactive reports are not generated unless there is overlapping experimental data. 

We also now extract the mbar error as our uncertainty value if only a single repeat is performed rather than the stdv which is supplied by gufe.

## Todos
Notable points that this PR has either accomplished or will accomplish.
- [x] make sure the predicted absolute values are valid even with no exp overlap
- [x] always have a non-zero error for FEC estimation.

## Questions
- [ ] Question 1 ..

## Status
- [x] Ready to go

## Developers certificate of origin
- [x] I certify that this contribution is covered by the MIT license as defined in our [LICENSE](https://github.com/choderalab/asapdiscovery/blob/main/LICENSE) and adheres to the [**Developer Certificate of Origin**](https://developercertificate.org/).

### CODE REVIEW

**Comment by jthorton** [comment]
looks like https://github.com/choderalab/asapdiscovery/pull/983 might have broken some of the imports used in testing.

**Comment by jthorton** [comment]
@hmacdope I have reversed a change made to one of the init files in the repo, let me know if you want me to change the imports instead and have the init blank? Also the live testing of postera seems to be broken.

**Comment by jthorton** [comment]
Just noticed the init is fixed on main so I have reversed the patch I added.

**Review by JenkeScheen — APPROVED** [review]
LGTM, great work!

**Pull request merged**
