### PR TITLE
Change `pytorch` to `torch` in pyproject.toml for `asapdiscovery.ml`

### LINKED ISSUE #166: Installing asapdiscovery-ml with `pip install -e .` fails due to `torch` vs `pytorch` pip issues
Installing asapdiscovery ml is complaining because the pip package is meant to be called `torch` not `pytorch`

### PR DESCRIPTION
**Pull request by hmacdope**
FIxes #166

### CODE REVIEW

**Comment by kaminow** [comment]
For some reason, the `conda` install package is `pytorch` and the `pip` package is just `torch`. Is the `pyproject.toml` file only for `pip`? Or will we need to include `pytorch` as well eventually?

**Comment by hmacdope** [comment]
@kaminow yeah py project.toml is only for pip so should just have torch.

**Review by kaminow — APPROVED** [review]
ok cool, sounds good then!

**Review by dotsdl — APPROVED** [review]
Thanks @hmacdope!

**Pull request merged**
