### PR TITLE
`ASAP-Alchemy`: Catch radicals in CDD downloading

### PR DESCRIPTION
**Pull request by jthorton**
## Description
This PR adds a check to remove radical molecules from the cdd downloader in asap-alchemy to make sure such molecules are not used as experimental references in FEC networks. We also make sure ligands created from smiles have explicit hydrogens. 

## Todos
Notable points that this PR has either accomplished or will accomplish.
- [x] Remove radicals from CDD download
- [x] make sure molecules from smiles have explicit hydrogens.

## Questions
- [ ] Question 1 ..

## Status
- [x] Ready to go

## Developers certificate of origin
- [x] I certify that this contribution is covered by the MIT license as defined in our [LICENSE](https://github.com/choderalab/asapdiscovery/blob/main/LICENSE) and adheres to the [**Developer Certificate of Origin**](https://developercertificate.org/).

### CODE REVIEW

**Review by hmacdope — APPROVED** [review]
LGTM @jthorton, thanks.

**Review by hmacdope — CHANGES_REQUESTED** [review]
@jthorton something  about adding explicit hydrogens is causing inconsistent inchikeys between Ligands and Complexes. Would you be able to have a look?

**Comment by hmacdope** [comment]
Important to get this in now as alchemy prep doesn't seem to work without it CC slackbot

**Comment by jthorton** [comment]
@hmacdope @apayne97 is a hero and has fixed the tests, this should be ready to go now!

**Review by hmacdope — APPROVED** [review]

**Pull request merged**
