### PR TITLE
Refactor ML v2 stuff

### LINKED ISSUE #781: Move v2 imports in `asapdiscovery-ml` to root level and rename to not have v2 in module and class names
As above

### PR DESCRIPTION
**Pull request by kaminow**
Rename all `v2` stuff in `asapdiscovery.ml` and move to top-level. (Also cut out old no longer used stuff? @hmacdope) Closes #781.

### CODE REVIEW

**Comment by hmacdope** [comment]
@kaminow is this ready for review or waiting to pull out more stuff.

**Comment by kaminow** [comment]
sorry yeah still working on some refactoring. marked as WIP to make that more obvious

**Comment by kaminow** [comment]
@hmacdope I think this should be ready now when you get a chance

**Review by hmacdope — APPROVED** [review]
This all looks great @kaminow, I am happy as long as CI comes back green.

**Comment by hmacdope** [comment]
Getting some negative Schnet scores @kaminow 

```
 @pytest.mark.parametrize("use_dask", [True, False])
    def test_schnet_scorer(results_multi, use_dask):
        scorer = SchnetScorer.from_latest_by_target("SARS-CoV-2-Mpro")
        scores = scorer.score(results_multi, use_dask=use_dask)
        assert len(scores) == 2
        assert scores[0].score_type == "schnet"
>       assert scores[0].score > 0.0
E       AssertionError: assert -1.6272869110107422 > 0.0
E        +  where -1.6272869110107422 = Score(score_type=<ScoreType.schnet: 'schnet'>, score=-1.6272869110107422, compound_name='test', smiles='c1ccc2c(c1)c(cc(=O)[nH]2)C(=O)NCCOc3cc(cc(c3)Cl)O[C@H]4CC(=O)N4', ligand_identifiers=None, ligand_inchikey='SNQHLYWSRJDLGK-FQEVSTJZSA-N', target_name='test', target_identifiers=None, complex_ligand_smiles='CNC(=O)CN1C[C@]2(CCN(C2=O)c3cncc4c3cc(cc4)Cl)c5cc(ccc5C1=O)Cl', probability=0.18000000715255737, units=<ScoreUnits.pIC50: 'pIC50'>).score
```

**Comment by kaminow** [comment]
well that's no good. I'll investigate

**Comment by hmacdope** [comment]
@kaminow I really want to get #832 and all close PRs probably need to go in first. as this is not strictly a repo issue I think we can just XFAIL this for now and come back with a new deployed schnet model? Would you be ok with this approach?

**Comment by kaminow** [comment]
I think that makes sense. my main worry with that approach though is giving garbage predictions to the med chemists, but I guess as long as we either unplug the schnet model from the project support pipeline, or tell them to disregard for now, it should be fine

**Comment by kaminow** [comment]
I do think it may be a more in depth issue to sort out though so probably makes sense to push ahead for now

**Comment by hmacdope** [comment]
> I do think it may be a more in depth issue to sort out though so probably makes sense to push ahead for now

I will XFAIL offending tests.

**Comment by hmacdope** [comment]
Removing from merge queue to first generate some project support data for @JenkeScheen with working `schnet` model.

**Review by hmacdope — CHANGES_REQUESTED** [review]
Temporary block

**Comment by kaminow** [comment]
@hmacdope at this point do you think it's worth the effort to rebuild the config files so that this can be merged in? we can leave the newer models commented out or something until I've figure out what's going on

**Comment by hmacdope** [comment]
I think we should just push on here.

**Review by hmacdope — APPROVED** [review]
Lets push forward here, invalidating old models (which are still experimental).

**Pull request merged**
