### PR TITLE
Add stop if no compounds docked.

### LINKED ISSUE #637: Multi-reference cross-docking workflow returns a "score_type" error
Script used to run docking:
```
#BSUB -J run_cross_docking
#BSUB -oo run_cross_docking_%I.out
#BSUB -eo run_cross_docking_%I.stderr
#BSUB -n 1
#BSUB -q cpuqueue
#BSUB -R rusage[mem=256]
#BSUB -W 24:00

source ~/.bashrc
conda activate asapdiscovery

asap-docking cross-docking \
--target SARS-CoV-2-Mpro \
--use-omega --allow-retries --allow-final-clash --multi-reference \
--structure-selector LeaveOneOutSelector \
--ligands /lila/data/chodera/asap-datasets/current/sars_01_prepped_v3/Mpro_combined_labeled_p_only_2d.sdf \
--structure-dir /lila/data/chodera/asap-datasets/current/sars_01_prepped_v3/pdb_cache_p_only \
--cache-dir /lila/data/chodera/asap-datasets/current/sars_01_prepped_v3/du_cache_p_only \
--cache-type DesignUnit \
--use-dask \
--dask-type lilac-cpu \
--output-dir /lila/data/chodera/asap-datasets/retro_docking/sars_fragalysis_retrospective/20231116_cross_docking_p_only_2d_multi_reference
```

Error traceback:
```
File "/lila/data/chodera/paynea/asapdiscovery/asapdiscovery-docking/asapdiscovery/docking/cli.py", line 228, in cross_docking
    cross_docking_workflow(inputs)
  File "/lila/data/chodera/paynea/asapdiscovery/asapdiscovery-docking/asapdiscovery/docking/workflows/cross_docking.py", line 243, in cross_docking_workflow
    scores_df = scorer.score(
  File "/lila/data/chodera/paynea/asapdiscovery/asapdiscovery-docking/asapdiscovery/docking/scorer_v2.py", line 338, in score
    return Score._combine_and_pivot_scores_df(results)
  File "/lila/data/chodera/paynea/asapdiscovery/asapdiscovery-docking/asapdiscovery/docking/scorer_v2.py", line 102, in _combine_and_pivot_scores_df
    df = df.pivot(
  File "/lila/home/paynea/miniforge3/envs/asapdiscovery/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/lila/home/paynea/miniforge3/envs/asapdiscovery/lib/python3.10/site-packages/pandas/core/frame.py", line 8567, in pivot
    return pivot(self, index=index, columns=columns, values=values)
  File "/lila/home/paynea/miniforge3/envs/asapdiscovery/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/lila/home/paynea/miniforge3/envs/asapdiscovery/lib/python3.10/site-packages/pandas/core/reshape/pivot.py", line 525, in pivot
    data_columns = [data[col] for col in columns_listlike]
  File "/lila/home/paynea/miniforge3/envs/asapdiscovery/lib/python3.10/site-packages/pandas/core/reshape/pivot.py", line 525, in <listcomp>
    data_columns = [data[col] for col in columns_listlike]
  File "/lila/home/paynea/miniforge3/envs/asapdiscovery/lib/python3.10/site-packages/pandas/core/frame.py", line 3807, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/lila/home/paynea/miniforge3/envs/asapdiscovery/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3804, in get_loc
    raise KeyError(key) from err
KeyError: 'score_type'
```

### PR DESCRIPTION
**Pull request by hmacdope**
Fixes #637

## Developers certificate of origin
- [X] I certify that this contribution is covered by the MIT license as defined in our [LICENSE](https://github.com/choderalab/asapdiscovery/blob/main/LICENSE) and adheres to the [**Developer Certificate of Origin**](https://developercertificate.org/).

### CODE REVIEW

**Review by apayne97 — APPROVED** [review]
Another case where #596 would reduce code duplication but LGTM

**Review by kaminow — APPROVED** [review]
this seems reasonable. do we also want to add a check before docking to make sure that we have stuff to dock? may save some time in terms of waiting for the Docker to be constructed, but could also go in a separate PR

**Comment by chrisiacovella** [comment]
This looks totally reasonable.  Since I'm not exactly familiar, let me ask a dumb question: Is raising an error the desired behavior or should some info be written to the data frame/csv file to indicate "this was tried and it didn't work"?

**Review by chrisiacovella — APPROVED** [review]

**Comment by hmacdope** [comment]
@chrisiacovella I think this should probably error, as 0 compounds docked = 0 useful results TBH, but good question.

**Pull request merged**
