### PR TITLE
Fix issue 260

### LINKED ISSUE #260: Investigate why DGL 1.1 breaks our weight comparisons for constructing GAT model
Investigate why DGL 1.1 breaks our weight comparisons for constructing GAT model

### PR DESCRIPTION
**Pull request by kaminow**
Add new GAT weights that are compatible with the new version of `dgl`. Closes #260.

### CODE REVIEW

**Review by hmacdope — CHANGES_REQUESTED** [review]
Can you also change the use of the old models in testing and in the run-docking-oe script? Also just  add a comment to the models yaml file about DGL compatibility

**Comment by kaminow** [comment]
oh yep, good call on both points

**Comment by kaminow** [comment]
@hmacdope ok I think I've done everything correctly, and the tests are green now which is a good sign. I wasn't sure whether to just update the old weights file on S3 or add a new one so I just added a new one to be safe, but feel free to adjust as you see fit

**Review by hmacdope — APPROVED** [review]
LGTM, thanks!

**Comment by hmacdope** [comment]
We need to fix the tolerance in some comparison, I'll do it one sec.

**Pull request merged**
