### PR TITLE
Fill in ML guides

### PR DESCRIPTION
**Pull request by kaminow**
Fill in notebooks and guides:

- [x] [docs/guides/using_ml_cli.md](https://github.com/choderalab/asapdiscovery/blob/main/docs/guides/using_ml_cli.md)
- [x] [examples/training_ml_models_on_asap_data.ipynb](https://github.com/choderalab/asapdiscovery/blob/main/examples/training_ml_models_on_asap_data.ipynb)
- [x] [examples/running_ml_inference.ipynb](https://github.com/choderalab/asapdiscovery/blob/main/examples/running_ml_inference.ipynb)

### CODE REVIEW

**Comment by kaminow** [comment]
running into an issue where the ML notebooks reference results from other sections. added a line in `docs/conf.py` to ignore `nbsphinx` errors for now, but that's probably not a good actual solution. would it make sense to upload some test files to an S3 bucket and point to those instead of the imaginary files I have currently @hmacdope?

**Comment by kaminow** [comment]
or alternatively is there a way to just have Sphinx render the notebooks but not run them? I don't think we want to do a full training run every time the docs are built

**Comment by hmacdope** [comment]
Can you use the files from the testsuite? That is often a good solution to use files that are useful and public. You can just use `get_test_file` inline

**Comment by kaminow** [comment]
oh yeah duh, that should work. thanks!

**Review by hmacdope — CHANGES_REQUESTED** [review]
Looks great, just a bit of introduction and citations for model types would be great in notebook and also CLI guide.

**Comment by kaminow** [comment]
@hmacdope addressed I think, lmk if this is what you were looking for or if I should add a bit more!

**Review by hmacdope — APPROVED** [review]
LGTM @kaminow! Thanks for pushing on this.

**Pull request merged**
