### PR TITLE
Add check during creation of FEC dataset that there are no duplicate ligands

### LINKED ISSUE #469: add check during setup that all ligands are unique, i.e. make sure there are no duplicates in the series

### PR DESCRIPTION
**Pull request by dotsdl**
## Description
Closes #469 and #465.

## Status
- [x] Ready to go

### CODE REVIEW

**Comment by dotsdl** [comment]
Needs an explicit test yet.

**Comment by JenkeScheen** [comment]
would it be possible to signal to the user *which* ligands are duplicates? Would make it easier to debug the input.

**Comment by dotsdl** [comment]
@JenkeScheen done! This is now ready for review!

**Review by JenkeScheen — APPROVED** [review]
LGTM! The only drawback to this approach is if we were to model two binding poses for one ligand. Currently we're not doing that (and we're not planning to in the near future). We can revisit/extend this functionality when we hit that.

**Comment by dotsdl** [comment]
@JenkeScheen I believe for same ligand, different binding poses the `SmallMoleculeComponent`s will hash differently, since they use the conformer information as part of this calculation. So we might be good to go there.

**Comment by dotsdl** [comment]
Test failures appear unrelated; merging!

**Pull request merged**
