### PR TITLE
Adding pre-commit ci

### PR DESCRIPTION
**Pull request by ijpulidos**
## Description
This enables a pre-commit ci for this repo that checks formatting (black) sorts imports (isort) and checks style (flake8).

This shouldn't change the annotations for git blame.

## Status
- [ ] Ready to go

### CODE REVIEW

**Comment by apayne97** [comment]
@ijpulidos are you using line length 80 or 88? we've been using 80

**Comment by ijpulidos** [comment]
> @ijpulidos are you using line length 80 or 88? we've been using 80

We are using black's default, that is 88, in my opinion 80 is too short. Of course, we can use 80 if folks think that's better.

**Comment by mikemhenry** [comment]
This PR is superseded by #151

**Comment by ijpulidos** [comment]
Closing, superseded by #151

**Pull request closed without merging**
