### PR TITLE
`ASAP-Alchemy`: Docs

### LINKED ISSUE #1028: asap-alchemy prep run outdated cli description
This is really minor and not urgent at all, but I noticed a mistake in the description when using  `asap-alchemy prep run` (i.e., the usage options from the `--help` argument). I just wanted to note it here for future releases. 

It says the core smarts (`--core-smarts`) are required when a default factory is used. It's not actually required anymore and the code runs just fine without specifying the core smarts. I assume this is just outdated from a previous version?

For reference, this is what the description says: *"factory_file: The name of the JSON file with the configured AlchemyPrepWorkflow, if not supplied the default will be     used but a core smarts must be provided. core_smarts: The SMARTS string used to identify the atoms in each ligand to be constrained. Required if the factory file is not supplied."*

### PR DESCRIPTION
**Pull request by jthorton**
## Description
This PR adds an example notebook tutorial on using the alchemy API to setup and run an alchemical free energy network and the corresponding CLI guide. 

Fixes #1028 

## Todos
Notable points that this PR has either accomplished or will accomplish.
- [x] Add tutorial notebook on prep, plan, submit, predict
- [x] add CLI guide on alchemy 

## Questions
- [ ] Question 1 ..

## Status
- [x] Ready to go

## Developers certificate of origin
- [x] I certify that this contribution is covered by the MIT license as defined in our [LICENSE](https://github.com/choderalab/asapdiscovery/blob/main/LICENSE) and adheres to the [**Developer Certificate of Origin**](https://developercertificate.org/).

### CODE REVIEW

**Comment by hmacdope** [comment]
@JenkeScheen could you review here?

**Comment by JenkeScheen** [comment]
ok, notebook is all corrected for typos, some phrasing edits and checked for general flow. Excellent stuff. @jthorton , did you also want to include `gather` and `predict` steps in this docs page?

**Review by JenkeScheen — APPROVED** [review]

**Comment by hmacdope** [comment]
@JenkeScheen @jthorton I will leave it up to you two to merge when ready.

**Comment by JenkeScheen** [comment]
@hmacdope I believe this is WIP, @jthorton is finalizing CLI docs

**Pull request merged**
