### PR TITLE
Fix batch training math

### PR DESCRIPTION
**Pull request by kaminow**
Realized that I left out a scaling term in the loss when using batches.

### CODE REVIEW

**Review by hmacdope — APPROVED** [review]

**Comment by kaminow** [comment]
@hmacdope I've been seeing this issue with the `docking` CI failing pretty frequently now. it always seems to be the same thing of different tests being collected. do you know what that is/what's causing it? it seems to go away if I re-run the CI workflow

**Comment by hmacdope** [comment]
@kaminow, not really I need to do some digging. Lets move to an issue as I agree annoying to always be re-running.

**Comment by kaminow** [comment]
gotcha. is there a way to push these PRs through without that check?

**Comment by hmacdope** [comment]
Lets try again otherwise can just force merge.

**Pull request merged**
